[versions]
accompanist = "0.37.3"
activity = "1.11.0"
androidxComposeBom="2025.10.01"
appCompat = "1.7.1"
autonomousappsSorting = "0.15"
autonomousappsUnused = "3.4.1"
billing = "8.0.0"
coil = "2.7.0"
compose = "2.9.4"
composeConstraintLayout = "1.1.1"
core = "1.17.0"
coroutinesCore = "1.10.2"
datastore = "1.1.7"
detektPlugin = "1.23.8"
firebaseBom = "34.5.0"
firebaseCrashlyticsPlugin = "3.0.6"
firebaseUi = "9.1.1"
googlePlayServices = "4.4.4"
googlePlayServicesAuth = "21.4.0"
googlePlayServicesLocation = "21.3.0"
gradlePlugin = "8.13.0"
hilt = "2.57.2"
hiltCommon = "1.3.0"
java = "17"
javaDesugaring = "2.1.5"
javaPoet = "1.13.0"
javaxInject = "1"
junit = "4.13.2"
kotlin = "2.2.21"
kotlinDatetime = "0.7.1"
kotlinxSerialization = "1.9.0"
ksp = "2.3.1"
material = "1.13.0"
mockk = "1.14.6"
moshi = "1.15.2"
navigation = "2.9.6"
okhttp = "5.3.0"
paging = "3.3.6"
retrofit = "3.0.0"
retrofitConverter = "1.0.0"
room = "2.8.3"
splashScreen = "1.0.1"
startup = "1.2.0"
timber = "5.0.1"
worker = "2.11.0"
workerHilt = "1.3.0"

[libraries]
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "gradlePlugin" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-window-size = { group = "androidx.compose.material3", name = "material3-window-size-class" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "composeConstraintLayout" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashScreen" }
androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "workerHilt" }
androidx-lifecycle-viewmodel-compose-android = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose-android", version.ref = "compose" }
androidx-work-runtime = { group = "androidx.work", name = "work-runtime", version.ref = "worker" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appCompat" }
billing = { group = "com.android.billingclient", name = "billing", version.ref = "billing" }
coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
core = { group = "androidx.core", name = "core", version.ref = "core" }
dagger = { group = "com.google.dagger", name = "dagger", version.ref = "hilt" }
datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
detekt = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detektPlugin" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-config = { group = "com.google.firebase", name = "firebase-config" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-crashlytics-gradle = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsPlugin" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage" }
firebase-ui-auth = { group = "com.firebaseui", name = "firebase-ui-auth", version.ref = "firebaseUi" }
google-services = { group = "com.google.gms", name = "google-services", version.ref = "googlePlayServices" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-android-gradle-plugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt" }
hilt-common = { group = "androidx.hilt", name = "hilt-common", version.ref = "hiltCommon" }
hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "hilt" }
hilt-ext-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltCommon" }
hilt-lifecycle-viewmodel-compose = { group = "androidx.hilt", name = "hilt-lifecycle-viewmodel-compose", version.ref = "hiltCommon" }
java-desugaring = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "javaDesugaring" }
java-poet = { group = "com.squareup", name = "javapoet", version.ref = "javaPoet" }
javax-inject = { group = "javax.inject", name = "javax.inject", version.ref = "javaxInject" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-metadata-jvm = { group = "org.jetbrains.kotlin", name = "kotlin-metadata-jvm", version.ref = "kotlin" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutinesCore" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesCore" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinDatetime" }
kotlinx-serialization-converter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofitConverter" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
ksp-gradle-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
mockk-core = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
navigation-common = { group = "androidx.navigation", name = "navigation-common", version.ref = "navigation" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
navigation-runtime = { group = "androidx.navigation", name = "navigation-runtime", version.ref = "navigation" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
paging-common = { group = "androidx.paging", name = "paging-common", version.ref = "paging" }
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }
play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "googlePlayServicesAuth" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "googlePlayServicesLocation" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
room-runtime-android = { group = "androidx.room", name = "room-runtime-android", version.ref = "room" }
startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "startup" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

[plugins]
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
deps-sorting = { id = "com.squareup.sort-dependencies", version.ref = "autonomousappsSorting" }
deps-unused = { id = "com.autonomousapps.dependency-analysis", version.ref = "autonomousappsUnused" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
